import { createFileRoute } from "@tanstack/react-router";
import { useServerFn } from "@tanstack/react-start";
import { useMutation } from "@tanstack/react-query";
import { useState } from "react";
import ReactMarkdown from "react-markdown";
import { DashboardShell, Panel } from "@/components/DashboardShell";
import { generateSchedule } from "@/lib/ai.functions";

export const Route = createFileRoute("/planner")({
  head: () => ({
    meta: [
      { title: "AI Task Planner — SCALEUP" },
      {
        name: "description",
        content:
          "Turn a messy task list into a priority-ranked daily or weekly schedule with the SCALEUP AI planner.",
      },
      { property: "og:title", content: "AI Task Planner — SCALEUP" },
      {
        property: "og:description",
        content: "Priority-ranked daily and weekly schedules, generated by AI.",
      },
    ],
  }),
  component: Planner,
});

function Planner() {
  const [tasks, setTasks] = useState("");
  const [horizon, setHorizon] = useState<"day" | "week">("day");
  const [hours, setHours] = useState(6);
  const run = useServerFn(generateSchedule);

  const plan = useMutation({
    mutationFn: () => run({ data: { tasks, horizon, hours } }),
  });

  return (
    <DashboardShell breadcrumb="Planner" title="Task planner">
      <div className="rise grid gap-4 lg:grid-cols-2">
        <Panel
          label="Planner input"
          sub="tasks · context"
          num="03"
          footer={
            <button
              onClick={() => plan.mutate()}
              disabled={!tasks.trim() || plan.isPending}
              className="w-full rounded-lg bg-aurora px-4 py-2.5 text-sm font-semibold text-ink transition-opacity disabled:opacity-40"
            >
              {plan.isPending ? "Planning…" : "Generate schedule"}
            </button>
          }
        >
          <div className="space-y-4 px-4 py-4">
            <div>
              <label className="font-mono text-[10px] uppercase tracking-[0.15em] text-mist">
                Tasks, deadlines and context
              </label>
              <textarea
                value={tasks}
                onChange={(e) => setTasks(e.target.value)}
                rows={9}
                placeholder={
                  "Send Meridian proposal (overdue)\nReview Colby contract redlines\nHire a second SDR\nPrep Northwind discovery call Thursday"
                }
                className="mt-2 w-full resize-none rounded-lg bg-ink-soft/70 px-3 py-2.5 text-sm leading-relaxed outline-none ring-1 ring-line placeholder:text-mist focus:ring-aurora/50"
              />
            </div>
            <div className="flex flex-wrap gap-4">
              <div>
                <p className="font-mono text-[10px] uppercase tracking-[0.15em] text-mist">
                  Horizon
                </p>
                <div className="mt-2 flex gap-1.5">
                  {(["day", "week"] as const).map((h) => (
                    <button
                      key={h}
                      onClick={() => setHorizon(h)}
                      className={`rounded-md px-3 py-1.5 text-xs font-medium capitalize ring-1 transition-colors ${
                        horizon === h
                          ? "bg-aurora/15 text-aurora ring-aurora/30"
                          : "text-mist ring-line hover:text-foreground"
                      }`}
                    >
                      {h}
                    </button>
                  ))}
                </div>
              </div>
              <div className="min-w-40 flex-1">
                <p className="font-mono text-[10px] uppercase tracking-[0.15em] text-mist">
                  Focus hours / day · {hours}
                </p>
                <input
                  type="range"
                  min={1}
                  max={12}
                  value={hours}
                  onChange={(e) => setHours(Number(e.target.value))}
                  className="mt-3 w-full accent-[var(--aurora)]"
                />
              </div>
            </div>
          </div>
        </Panel>

        <Panel label="Generated plan" sub="priority-ranked" num="03" className="min-h-80">
          <div className="flex-1 px-4 py-4">
            {plan.isPending && (
              <p className="font-mono text-xs text-mist">Ranking your tasks…</p>
            )}
            {plan.isError && (
              <p className="rounded-lg bg-destructive/15 px-3 py-2 text-xs text-destructive ring-1 ring-destructive/30">
                Couldn't generate a schedule. Please try again.
              </p>
            )}
            {!plan.isPending && !plan.data && !plan.isError && (
              <p className="text-sm text-mist">
                Paste your task list and SCALEUP will sequence it by priority and
                available hours.
              </p>
            )}
            {plan.data && (
              <div className="space-y-2 rounded-lg bg-ink-soft/40 p-3 text-sm leading-relaxed text-foreground/90 ring-1 ring-line [&_h2]:font-display [&_h2]:text-base [&_h2]:font-semibold [&_h3]:font-display [&_h3]:text-sm [&_h3]:font-semibold [&_li]:ml-4 [&_li]:list-disc [&_strong]:text-foreground">
                <ReactMarkdown>{plan.data.text}</ReactMarkdown>
              </div>
            )}
          </div>
        </Panel>
      </div>
    </DashboardShell>
  );
}
